### ISSUE TITLE
Boss mod

### ISSUE THREAD

**Issue by Darkpriestx** [kesava-wow/kuinameplates-customs#14]
After reinstalling the game, the energy icon disappeared(boss mod is on) 
![2](https://user-images.githubusercontent.com/20583560/49181914-c6f71f80-f369-11e8-8c69-82edff25ba24.png)

**Comment by kesava-wow** [comment]
What's the output of: /knp dump
It should open a window you can copy out of. It tells me what version you're on, what your settings are, and what external modifications you have installed.

**Comment by Darkpriestx** [comment]
2.18.1 2.3
{ ["profile"] = "default" }
{ ["auras_on_personal"] = false, ["auras_icon_normal_size"] = 33, ["bot_vertical_offset"] = 13, ["auras_hide_all_other"] = true, ["level_text"] = true, ["health_text_friend_max"] = 3, ["name_vertical_offset"] = 13.5, ["health_text_friend_dmg"] = 4, ["health_text"] = true, ["auras_sort"] = 1, ["font_size_small"] = 13, ["nameonly_health_colour"] = false, ["fade_non_target_alpha"] = 1, ["text_vertical_offset"] = -10, ["execute_enabled"] = false, ["bar_texture"] = "ElvUI Norm", ["auras_show_purge"] = false, ["font_size_normal"] = 13, ["target_glow_colour"] = { [1] = 1, [2] = 1, [3] = 1, [4] = 1 }, ["frame_width_minus"] = 170, ["frame_width"] = 170, ["auras_time_threshold"] = -1, ["frame_height"] = 22, ["hide_names"] = false, ["health_text_hostile_max"] = 4, ["auras_icon_minus_size"] = 33, ["auras_centre"] = false, ["font_face"] = "PT Sans Narrow", ["tankmode_other_colour"] = { [1] = 0.57254901960784, [2] = 0, [3] = 0 }, ["auras_icon_squareness"] = 1, ["castbar_height"] = 10, ["auras_pulsate"] = false, ["auras_show_all_self"] = true }
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, [Execute], Fading, GuildText, PlayerAnchor, TankMode, BossMods, [CombatToggle], BarAnimation, ArenaID, Target

**Comment by Darkpriestx** [comment]
I save my settings) When i can see that (enable or disable certain auras on nameplates in their config interfaces.) and may be i can disable boss mod do relog and enable(do relog) that can help me?

**Comment by kesava-wow** [comment]
That depends on what boss mod you're using - I couldn't tell you exactly where they put their options.

I just checked DBM and BigWigs' code though, and neither of them add an energy icon on Ghuun. Was it perhaps added by a WeakAura, or something like that?

**Comment by Darkpriestx** [comment]
I use DBM and ask my friend, he use only kui+dbm+wa(they are common) and he see energy icon. We start use that in antorus on aggromar(mythic) to see energy Ember of Taeshalach

**Comment by Darkpriestx** [comment]
Oh... sry i stupid thats was WA sry man thanks for try help)
