### ISSUE TITLE
Custom LOS Fade

### ISSUE THREAD

**Issue by vash12788** [kesava-wow/kuinameplates-customs#16]
After the 8.1 update I get an error after loading and the custom fade doesn't function.

5x Kui_Nameplates\messages.lua:540: Out of date plugin `LOSFader` ignored
[C]: in function `error'
Kui_Nameplates\messages.lua:540: in function `NewPlugin'
Kui_Nameplates_Custom\custom-Custom.lua:14: in main chunk

Locals:
(*temporary) = "Out of date plugin `LOSFader` ignored"

**Comment by Stanzilla** [comment]
even after bumping the minor version to get it to load, it seems to always fade out everything

**Comment by kesava-wow** [comment]
yes. the sizer was removed in 2.18.2 so this needs a more complex fix.

**Comment by Stanzilla** [comment]
could have waited with the release then, meany!
