### ISSUE TITLE
Not working with 8.2 anymore

### ISSUE THREAD

**Issue by anonyzero** [kesava-wow/kuinameplates-customs#21]
Date: 2019-06-27 00:56:15
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Kui_Nameplates_Core\create.lua line 414:
   Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: KuiNamePlate1:SetPoint.
Debug:
   [C]: ?
   [C]: SetPoint()
   Kui_Nameplates_Core\create.lua:414: UpdateFrameSize()
   Kui_Nameplates_Core\hook.lua:54: func()
   Kui_Nameplates\messages.lua:128: DispatchMessage()
   Kui_Nameplates\nameplate.lua:74: OnShow()
   Kui_Nameplates\nameplate.lua:67: OnUnitAdded()
   Kui_Nameplates\addon.lua:87: ?()
   Kui_Nameplates\addon.lua:130:
      Kui_Nameplates\addon.lua:127
Locals:

**Comment by kesava-wow** [comment]
I need to know what customs you're using in order to help.

**Comment by anonyzero** [comment]
results from knp dump:

2.24 2.4+c
enUS PRIEST
{ ["profile"] = "priest1" }
{ ["nameonly_all_enemies"] = true, ["cvar_overlap_v"] = 1.2, ["auras_icon_normal_size"] = 40, ["bot_vertical_offset"] = 0, ["execute_colour"] = { [1] = 1, [2] = 1, [3] = 1 }, ["name_text"] = false, ["castbar_height"] = 10, ["auras_cd_offset_y"] = 0, ["name_vertical_offset"] = 2, ["health_text_hostile_dmg"] = 2, ["auras_icon_squareness"] = 0.69999998807907, ["auras_sort"] = 1, ["castbar_icon"] = false, ["cvar_max_distance"] = 80, ["bar_texture"] = "ElvUI Blank", ["auras_offset"] = 8, ["colour_hated"] = { [1] = 0.13725490196078, [2] = 0.29411764705882, [3] = 0.68627450980392 }, ["frame_width_personal"] = 127, ["target_arrows"] = true, ["target_glow_colour"] = { [1] = 1, [2] = 1, [3] = 1, [4] = 1 }, ["cvar_personal_show_combat"] = false, ["font_style"] = 1, ["frame_width"] = 140, ["auras_colour_short"] = { [1] = 1, [2] = 0, [3] = 0 }, ["auras_cd_size"] = 17, ["classpowers_enable"] = false, ["auras_cd_offset_x"] = 0, ["frame_height_minus"] = 13, ["colour_player"] = { [1] = 0.59607843137255, [2] = 0.41176470588235, [3] = 1 }, ["fade_all"] = true, ["auras_centre"] = false, ["frame_glow_size"] = 7, ["fade_avoid_tracked"] = true, ["health_text_hostile_max"] = 2, ["auras_colour_medium"] = { [1] = 1, [2] = 1, [3] = 1 }, ["cvar_clamp_top"] = 0.0099999979138374, ["class_colour_friendly_names"] = false, ["nameonly_target"] = false, ["level_text"] = true, ["health_text"] = true, ["nameonly"] = false, ["cvar_enable"] = true, ["font_size_normal"] = 10, ["castbar_colour"] = { [1] = 0.55686274509804, [2] = 0.87450980392157, [3] = 0.90588235294118 }, ["nameonly_no_font_style"] = true }
HealthBar, [ClassPowers], NameText, RaidIcon, Highlight, LevelText, CombatUpdate, CastBar, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, PlayerAnchor, Fading, GuildText, BarAnimation, BossMods, ArenaID, [CombatToggle], SimpleAuraMods, MythicAuras, CustomInjector, ColourBarByName, LOSFader, Target

**Comment by anonyzero** [comment]
Here's my dump file. I noticed I had los-fade loaded, in custom as well as fading in knp. Disabled los-fade in custom injector and now it loads without issues.

2.24 2.4+c
enUS PRIEST
{ ["profile"] = "testing" }
{ ["nameonly_all_enemies"] = true, ["cvar_overlap_v"] = 1.2, ["auras_icon_normal_size"] = 40, ["bot_vertical_offset"] = 0, ["execute_colour"] = { [1] = 1, [2] = 1, [3] = 1 }, ["name_text"] = false, ["castbar_height"] = 10, ["auras_cd_offset_y"] = 0, ["name_vertical_offset"] = 2, ["health_text_hostile_dmg"] = 2, ["auras_icon_squareness"] = 0.69999998807907, ["auras_sort"] = 1, ["castbar_icon"] = false, ["cvar_max_distance"] = 80, ["bar_texture"] = "ElvUI Blank", ["auras_offset"] = 8, ["colour_hated"] = { [1] = 0.13725490196078, [2] = 0.29411764705882, [3] = 0.68627450980392 }, ["frame_width_personal"] = 127, ["target_arrows"] = true, ["target_glow_colour"] = { [1] = 1, [2] = 1, [3] = 1, [4] = 1 }, ["cvar_personal_show_combat"] = false, ["font_style"] = 1, ["frame_width"] = 140, ["auras_colour_short"] = { [1] = 1, [2] = 0, [3] = 0 }, ["auras_cd_size"] = 17, ["classpowers_enable"] = false, ["auras_cd_offset_x"] = 0, ["nameonly"] = false, ["colour_player"] = { [1] = 0.59607843137255, [2] = 0.41176470588235, [3] = 1 }, ["fade_all"] = true, ["auras_centre"] = false, ["frame_glow_size"] = 7, ["fade_avoid_tracked"] = true, ["health_text_hostile_max"] = 2, ["auras_colour_medium"] = { [1] = 1, [2] = 1, [3] = 1 }, ["cvar_clamp_top"] = 0.0099999979138374, ["class_colour_friendly_names"] = false, ["nameonly_target"] = false, ["level_text"] = true, ["health_text"] = true, ["frame_height_minus"] = 13, ["cvar_enable"] = true, ["font_size_normal"] = 10, ["castbar_colour"] = { [1] = 0.55686274509804, [2] = 0.87450980392157, [3] = 0.90588235294118 }, ["nameonly_no_font_style"] = true }
HealthBar, [ClassPowers], NameText, RaidIcon, Highlight, LevelText, CombatUpdate, CastBar, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, PlayerAnchor, Fading, GuildText, BarAnimation, BossMods, ArenaID, [CombatToggle], SimpleAuraMods, CustomInjector, ColourBarByName, MythicAuras, Target

**Comment by kesava-wow** [comment]
Delete the LOS fader custom script.

**Comment by kesava-wow** [comment]
OH I missed your edit. I guess we were typing at the same time.

Good! I'm always glad when something isn't strictly my fault.
