### ISSUE TITLE
KNP custom injector not loading older lua files

### ISSUE THREAD

**Issue by anonyzero** [kesava-wow/kuinameplates-customs#28]
This is also with the new "Temp" custom injector uploaded a week ago.

-----

Dump file: 

2.26.3e 2.5+c
enUS MAGE
{profile=default}
{auras_centre=false,auras_icon_normal_size=40,auras_icon_squareness=0.7,auras_offset=8,auras_sort=1,bar_texture=ElvUI Blank,bot_vertical_offset=0,castbar_colour={1=0.557,2=0.875,3=0.906},castbar_height=10,castbar_icon=false,class_colour_friendly_names=false,classpowers_enable=false,colour_hated={1=0.137,2=0.294,3=0.686},cvar_clamp_top=0.01,cvar_enable=true,cvar_overlap_v=0.8,cvar_personal_show_combat=false,execute_colour={1=1,2=1,3=1},fade_all=true,font_size_normal=10,font_style=1,frame_glow_size=7,frame_height=30,frame_height_minus=13,frame_width=140,health_text=true,health_text_hostile_dmg=2,health_text_hostile_max=2,level_text=true,name_text=false,name_vertical_offset=-20,nameonly=false,nameonly_all_enemies=true,nameonly_no_font_style=true,nameonly_target=false,target_arrows=true,target_glow_colour={1=1,2=1,3=1,4=1}}
HealthBar, [ClassPowers], NameText, RaidIcon, Highlight, LevelText, CombatUpdate, CastBar, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, PlayerAnchor, Fading, GuildText, Quest, BossMods, [CombatToggle], BarAnimation, ArenaID, HealthBarByName, HideAuraCount, SimpleAuraMods, Target

-----

1x Kui_Nameplates\messages.lua:536: Ignoring out of date plugin: `MythicAuras`
[string "=[C]"]: in function `error'
[string "@Kui_Nameplates\messages.lua"]:536: in function `NewPlugin'
[string "@Kui_Nameplates_Custom\custom.mythicplus.lua"]:7: in main chunk

-----

1x Kui_Nameplates\messages.lua:536: Ignoring out of date plugin: `ColourBarByName`
[string "=[C]"]: in function `error'
[string "@Kui_Nameplates\messages.lua"]:536: in function `NewPlugin'
[string "@Kui_Nameplates_Custom\custom.name-and-target-colour.lua"]:7: in main chunk

-----

**Comment by anonyzero** [comment]
After a bit of fiddling around as a complete rookie, I've compared the LUA files from custom colours and mythicauras with the other weakauras and noticed that there was a difference.

Changing versions from 4 to 6 resolved the problem
`local mod = addon:NewPlugin('ColourBarByName',101,4)`

`local mod = addon:NewPlugin('ColourBarByName',101,6)`

**Comment by kesava-wow** [comment]
That just means I haven't tested them with the latest versions of KNP. They probably work fine if you manually bump the max minor like that, though.
